#
# Inspired in the original defaults recipe at:
#   https://github.com/ContinuumIO/anaconda-recipes/tree/master/lighttpd
#
# This updates to newer versins, builds with bzip2 and pcre support and
# includes a more comprehensive example of MIME config.
#
# See also:
#  - https://redmine.lighttpd.net/projects/lighttpd/wiki/InstallFromSource
#  - https://redmine.lighttpd.net/projects/lighttpd/wiki/OptionalLibraries
#

{% set version = "1.4.50" %}
{% set build_number= "0" %}

package:
  name: lighttpd
  version: {{ version }}

source:
  fn: lighttpd-{{ version }}.tar.gz
  url: http://download.lighttpd.net/lighttpd/releases-1.4.x/lighttpd-{{ version }}.tar.gz
  sha256: c9a9f175aca6db22ebebbc47de52c54a99bbd1dce8d61bb75103609a3d798235

build:
  number: {{ build_number }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - zlib
    - bzip2
    - pcre 8
  run:
    - zlib
    - bzip2
    - pcre 8

test:
  files:
    - lighttpd.conf
  commands:
    - lighttpd -h
    - lighttpd -v
    - lighttpd -t -f lighttpd.conf

about:
  home: http://www.lighttpd.net/
  license: BSD
  license_file: COPYING
  summary: Light, fast web server
  description: |
    Lighttpd is rapidly redefining the efficiency of a webserver. It is
    designed and optimized for high performance environments. With a small
    memory footprint compared to other web-servers, effective management of
    the cpu-load, and an advanced feature set, lighttpd is the perfect
    solution for every server that is suffering load problems.
  doc_url: http://redmine.lighttpd.net/projects/lighttpd/wiki
  doc_source_url: http://redmine.lighttpd.net/projects/lighttpd/repository/revisions/master/show/doc
  dev_url: https://github.com/lighttpd

extra:
  recipe-maintainers:
    - sdvillal
